# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lorenzo Pannacci
title: Master's Student @ M.Sc. Data Science, Sapienza Università di Roma
email: lorenzo.pannacci.01@gmail.com
website: lorenzopannacci.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lorenzopannacci
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: lorenzo-pannacci
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Kaggle link
  icon: fab fa-kaggle
  url: https://www.kaggle.com/lorenzopannacci
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Work In Progress!

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: M.Sc. Data Science
        caption: 2023 - 2025
        sub_title: Sapienza Università di Roma
        description: | # this will include new lines to allow paragraphs
          I am currently enrolled as a second year student following the Honours' Programme.

      - layout: left
        title: B.Sc. Computer and System Engineering
        caption: 2020 - 2023
        sub_title: Sapienza Università di Roma
        description: | # this will include new lines to allow paragraphs
          Grade: 110 / 110 cum laude

          Thesis: "Generating and Using Synthetic Data from Three-Dimensional Scenes for Object Detection"

      - layout: left
        title: High School Diploma, Liceo Scientifico Tradizionale
        caption: 2015 - 2020
        sub_title: Liceo Statale Democrito
        description: | # this will include new lines to allow paragraphs
          Grade: 100 / 100 cum laude

          During my time in high school, I participated in various student competitions of math and computer science at school, regional, and national levels.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Yao's Garbled Circuits
        link: github.com/LorenzoPannacci/DPS-FinalProject
        link_text: Github repository
        description: | # this will include new lines to allow paragraphs
          I implemented from scratch in Python all the components required for Garbled Circuits, a cryptographic protocol for secure two-party computation, including socket communication and cryptographic primitives as asymmetric encryption and oblivious transfer.

      - layout: left
        title: Recurrent Neural Network for Music Generation
        link: github.com/LorenzoPannacci/NNDS-FinalProject
        link_text: Github repository
        description: | # this will include new lines to allow paragraphs
          I implemented from scratch in JAX a LSTM-based recurrent neural network and trained it on a large collection of MIDI files for the task of music generation.

      - layout: left
        title: Distribuited Graph Convolutional Networks
        link: github.com/LorenzoPannacci/SPML-FinalProject
        link_text: Github repository
        description: | # this will include new lines to allow paragraphs
          I implemented from scratch in JAX the distribuited training and inference algorithms for graph convolutional networks described in the paper "Distributed Training of Graph Convolutional Networks".

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
