# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Master's Student @ M.Sc. Data Science, Sapienza Università di Roma
title: Lorenzo Pannacci
email: lorenzo.pannacci.01@gmail.com
website: lorenzopannacci.github.io
description: My name is Lorenzo Pannacci and I am a Master student in Data Science. This is my personal website and portfolio containing Github projects.

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lorenzopannacci
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: lorenzo-pannacci
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Kaggle link
  icon: fab fa-kaggle
  url: https://www.kaggle.com/lorenzopannacci
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Work In Progress!

content:

#############
# EDUCATION #
#############

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:


      # master's degree
      - layout: left
        border: weak
        title: M.Sc. Data Science
        caption: 2023 - 2025
        sub_title: Sapienza Università di Roma
        description: | # this will include new lines to allow paragraphs
          I am currently enrolled as a second year student following the Honours' Programme and working on my thesis.

          Recipient of "<i>Exam bonus</i>" merits from Sapienza University.


      # bachelor's degree
      - layout: left
        border: weak
        title: B.Sc. Computer and System Engineering
        caption: 2020 - 2023
        sub_title: Sapienza Università di Roma
        description: | # this will include new lines to allow paragraphs
          Grade: 110 / 110 cum laude

          Recipient of "<i>Outstanding student</i>" merits from Sapienza University.

          ---

          In my thesis "<i>Generazione e utilizzo di dati sintetici da scenetridimensionali per l’object detection</i>" (<i>Generating and Using Synthetic Data from Three-Dimensional Scenes for Object Detection</i>) I explored the generation of synthetic data from 3D environments to mitigate the domain shift between training and test data in the setting of precision agriculture. Using NVIDIA Omniverse, I created synthetic datasets of grape clusters and combined them with real-world data to train YOLOv5 object detection models.
          
          The results demonstrated that synthetic data effectively reduced the domain gap, improving object detection accuracy in the target environment. Additionally, I achieved a small performance boost even within the original domain, highlighting the broader potential of synthetic data in supervised learning for computer vision tasks.


      # high school
      - layout: left
        title: High School Diploma, Liceo Scientifico Tradizionale
        caption: 2015 - 2020
        sub_title: Liceo Statale Democrito
        description: | # this will include new lines to allow paragraphs
          Grade: 100 / 100 cum laude

          For my performance at the maturity exam I have been awarded by my school and the <i>Ministry of Education and Merit</i> and my name has been recorded inside the "<a href="https://www.indire.it/eccellenze/" target="_blank" rel="noopener noreferrer">Albo Nazionale delle Eccellenze</a>" (<i>National Register of Excellence</i>).

          ---

          During my time in high school, I participated in various student competitions of math and computer science at school, regional, and national levels both alone and in teams.

############
# PROJECTS #
############

  - title: Featured Projects
    layout: list # Type of content section (list/text)
    content:


      # spml final project
      - layout: left
        border: weak
        title: Distribuited Graph Convolutional Networks
        sub_title: February 2025
        additional_links:
        - title: Github repository
          icon: fab fa-github
          url: github.com/LorenzoPannacci/SPML-FinalProject
        description: | # this will include new lines to allow paragraphs
          I implemented from scratch in JAX the distribuited training and inference algorithms for graph convolutional networks described in the paper "<a href="https://ieeexplore.ieee.org/document/9303371" target="_blank" rel="noopener noreferrer"><i>Distributed Training of Graph Convolutional Networks</i></a>" and compared their performances on different datasets varying the amount of agents and against the non-distribuited implementation, which code I also wrote from scratch in JAX.


      # dps final project
      - layout: left
        border: weak
        title: Yao's Garbled Circuits
        sub_title: January 2025
        additional_links:
        - title: Github repository
          icon: fab fa-github
          url: github.com/LorenzoPannacci/DPS-FinalProject
        description: | # this will include new lines to allow paragraphs
          I implemented from scratch in Python the components required for Yao's Garbled Circuits, a cryptographic protocol for secure two-party computation, including the parsing of circuits form file (described in the "<a href="https://nigelsmart.github.io/MPC-Circuits/old-circuits.html" target="_blank" rel="noopener noreferrer">Bristol Format</a>"), socket communication and cryptographic primitives as asymmetric encryption and Oblivious Transfer.
          
          The result of many example circuits is provided, as integer and float operations, hashing, encryption and coin tossing.


      # binm final project
      - layout: left
        border: weak
        title: Drug Repurposing for Retinal Distrophy
        sub_title: January 2025
        additional_links:
        - title: Github repository
          icon: fab fa-github
          url: github.com/LorenzoPannacci/BINM-FinalProject
        description: | # this will include new lines to allow paragraphs
          My team and I conducted a comparative analysis of state-of-the-art disease gene prioritization algorithms (e.g. DIAMOnD, DiaBLE) and applied them to retinal dystrophy data, with the primary objective of drug repurposing.
          
          We carried out every stage of the pipeline, including data preprocessing, algorithm implementation, and result interpretation. Our findings were then synthesized into a comprehensive report.


      # nnds final project
      - layout: left
        border: weak
        title: Recurrent Neural Network for Music Generation
        sub_title: December 2024
        additional_links:
        - title: Github repository
          icon: fab fa-github
          url: github.com/LorenzoPannacci/NNDS-FinalProject
        description: | # this will include new lines to allow paragraphs
          I implemented from scratch in JAX all the layers and optimization algorithms for an LSTM-based Recurrent Neural Network, including LSTM layers, embedding layers, dropout layers and the RMSprop training algorithm. The network is trained for the autoregressive task of music generation on a large collection of tokenized MIDI files, resulting in 24 million training samples.

          Listenable examples are provided by processing converting the generated sequences back into MIDI files and converting them into audio using a music synthesizer.


      # nbd homework
      - layout: left
        border: weak
        title: Comparison of Data Center Network Topologies
        sub_title: May 2024
        additional_links:
        - title: Github repository
          icon: fab fa-github
          url: https://github.com/LorenzoPannacci/NBD-HW1
        description: | # this will include new lines to allow paragraphs
          I designed and implemented a scenario to confront two well-known data center networking topologies for distribuited computing (Fat-Tree and Jellyfish), against a baseline of a non-distribuited computation. Using simulations I obtained data about their job running cost including overhead and mean response time varying the amount of servers and summarized my findings in plots.


      # mqi final project
      - layout: left
        border: weak
        title: Lecture on Datalog and Negation
        sub_title: September 2023
        additional_links:
        - title: Github repository
          icon: fab fa-github
          url: https://github.com/LorenzoPannacci/MQI-FinalProject
        description: | # this will include new lines to allow paragraphs
          I researched, wrote and presented a lecture about a comprehensive overview of Datalog and the introduction of negation within the language, covering the foundations of Horn clauses up to advanced semantic extensions like perfect, well-founded, and stable models, with a focus on the computational and logical implications of negation.


      # tlc homeworks
      - layout: left
        title: Network Simulations, Traffic Analysis and Visualization
        sub_title: December 2022
        additional_links:
        - title: Github repository 1
          icon: fab fa-github
          url: https://github.com/LorenzoPannacci/TLC-HW1
        - title: Github repository 2
          icon: fab fa-github
          url: https://github.com/LorenzoPannacci/TLC-HW2
        description: | # this will include new lines to allow paragraphs
          My team and I used the C++ library  <i>ns-3</i> to create network simulations of TCP/UDP connections between machines both in wired and WLAN mobile enviroments and then used the software <i>Wireshark</i> to perform packet traffic analysis and visualized the communication using <i>NetAnim</i>.

###########################
# AWARDS AND COMPETITIONS #
###########################

  - title: Awards and Competitions
    layout: list # Type of content section (list/text)
    content:

      # training camp
      - layout: left
        border: weak
        title: 1st place @ Training Camp - Multimodal Learning
        sub_title: September 2024
        additional_links:
        - title: Github repository
          icon: fab fa-github
          url: github.com/LorenzoPannacci/TrainingCamp-Leonardo
        - title: Kaggle competition
          icon: fab fa-kaggle
          url: kaggle.com/competitions/multimodal-classification-tc-sep-2024
        description: | # this will include new lines to allow paragraphs
          Me and my team won the first place in the competition made by Leonardo Company S.p.A. for the Training Camp of September 2024 at the Master of Science in Data Science at Sapienza about "<i>Multimodal Learning from Language and Vision Processing Neural Networks</i>".

          The competition was about reverse-engineering a image-generating model by extracting the hidden context it has been given starting from the generated image and its textual description.

      # pcto roma 3
      - layout: left
        border: weak
        title: Best Student @ PCTO Roma Tre - "Da Grande Farò il Biologo"
        sub_title: February 2019
        description: | # this will include new lines to allow paragraphs
          During my 4th year of high school as part of "Percorsi per le Competenze Trasversali e per l'Orientamento" (<i>Paths for transversal skills and orientation</i>) I have been selected as a representative for my school for the project "Da Grande Farò il Biologo", hosted by Roma Tre university's biology department.

          The project consisted in a full-time week of lectures and laboratory sessions made by biology professors of the university and ended with a final examination. Thanks to my score in the evaluation I have been awarded the possibility of entering the bachelor's course of biology at Roma Tre university without taking the admission test.

      # honourable mention
      - layout: left
        title: Honourable Mention @ GAMUN 2018
        sub_title: May 2018
        description: | # this will include new lines to allow paragraphs
          During my 3rd year of high school as part of "Percorsi per le Competenze Trasversali e per l'Orientamento" (<i>Paths for transversal skills and orientation</i>) I participated in the Global Action Model United Nations (GAMUN) 2018, a simulation of United Nations' diplomatic negotiations hosted at the World Food Programme (WFP) headquarters in Rome and my performances earned me an Honourable Mention at the end of the event.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
